### ISSUE TITLE
应更新新学期课程安排

### ISSUE THREAD

**Issue by danyang685** [skyzh/SJTU_Diploma#1]
“秋季学期开课表”应该更新为“春季学期开课表”，并更新LessonArrangeForOthers数据。新教务系统变动较大，对外发布的数据格式也有变化。下附我下载到的完整课程安排数据。
[LessonArrange.zip](https://github.com/SkyZH/SJTU_Diploma/files/2768034/LessonArrange.zip)

**Comment by skyzh** [comment]
Thanks for your contribution! I'll update once I had time.

**Comment by danyang685** [comment]
已更新 #4
